### ISSUE TITLE
ExternalJsFileLoader service does not support server side rendering

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#10201]
**Describe the bug**
When using the `ExternalJsFileLoader` to e.g. load the google maps api via `GoogleMapRendererService`, the method `load` uses the code `this.document.createElement('script')` to create the script tag on the document.

Accessing the document like this throughs an error, when executing the code in Node JS (SSR).

**Tell us the version of Spartacus**
- Library version: 3.0.0-rc.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Generate a new Spartacus Storefront
2. Follow Steps to activate Server Side Rendering
3. Start local instance
4. See error in console:

```
ERROR ReferenceError: document is not defined
    at ExternalJsFileLoader.load (/Users/jwidmer/projects/conforama/workspace/js-storefront/conforama-storefront/dist/conforama-storefront-server/main.js:219361:9)
    at GoogleMapRendererService.renderMap (/Users/jwidmer/projects/conforama/workspace/js-storefront/conforama-storefront/dist/conforama-storefront-server/main.js:108067:39)
    at StoreFinderMapComponent.renderMap (/Users/jwidmer/projects/conforama/workspace/js-storefront/conforama-storefront/dist/conforama-storefront-server/main.js:124587:39)
    at StoreFinderMapComponent.ngOnChanges (/Users/jwidmer/projects/conforama/workspace/js-storefront/conforama-storefront/dist/conforama-storefront-server/main.js:124575:18)
    at StoreFinderMapComponent.rememberChangeHistoryAndInvokeOnChangesHook (/Users/jwidmer/projects/conforama/workspace/js-storefront/conforama-storefront/dist/conforama-storefront-server/main.js:149714:14)
```

**Expected behavior**
The method `externalJsFileLoader.load` can be used in both SSR and CSR scenarios

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Additional context**
In the `constructor` of the `ExternalJsFileLoader`, the document is injected by using the `type` `any`. Should that maybe changed to `constructor(@Inject(DOCUMENT) protected document: DOCUMENT) {}` ?

**Comment by janwidmer** [comment]
@Xymmer thanks for setting the milestone labels. Do you already have a timeline when this will be fixed? (Our go live is expected to be End of january..)

**Comment by janwidmer** [comment]
Additionally, line 40 needs to be adjusted from `document.head.appendChild(script);` to `this.document.head.appendChild(script);` :)

**Comment by janwidmer** [comment]
Another Input:
As most 3rd Party Scripts complain, when they get included in the page twice (Code get's executed in Server Side rendering and again in Client Side Rendering) (e.g. Google Maps), it would be great, if there would be an option within the load option to disable it for Server side rendering:

```
interface ILoadConfig {
	callback?: EventListener;
	errorCallback?: EventListener;
	loadInSSR?: boolean;
}

public load(src: string, params?: object, config?: ILoadConfig): void {
	if (isPlatformServer(this.platformId) && config?.loadInSSR === false) return;
	
	// ... rest of the code
}
```

**Comment by mirkosoft** [comment]
@janwidmer Spartacus 3.0.2 has been released and contains the fix for this issue.

**Comment by janwidmer** [comment]
@mirkosoft thanks, will do the update soon
