### ISSUE TITLE
[needs triage] ERROR in Error: Internal error: unknown identifier undefined when trying to build Angular 10 app with Sparatcus 3.0 components and Ivy disabled

### ISSUE THREAD

**Issue by dinolaktasic** [SAP/spartacus#10530]
I created new Angular 10 application, added Spartacus 3.0 packages and disabled Ivy in tsconfig.json angularCompilerOptions. In app.module.ts I imported B2cStorefrontModule (no matter which spartacus module I import the build error is same). After I tried to build with --prod flag I got the error:

ERROR in Error: Internal error: unknown identifier undefined
    at Object.importExpr$1 [as importExpr] (C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler\bundles\compiler.umd.js:27372:27)
    at tokenExpr (C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler\bundles\compiler.umd.js:23933:43)
    at providerDef (C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler\bundles\compiler.umd.js:23859:24)
    at C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler\bundles\compiler.umd.js:24029:81
    at Array.map (<anonymous>)
    at NgModuleCompiler.compile (C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler\bundles\compiler.umd.js:24029:48)
    at AotCompiler._compileModule (C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler\bundles\compiler.umd.js:27317:36)
    at C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler\bundles\compiler.umd.js:27236:70
    at Array.forEach (<anonymous>)
    at AotCompiler._compileImplFile (C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler\bundles\compiler.umd.js:27236:23)
    at C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler\bundles\compiler.umd.js:27226:74
    at Array.map (<anonymous>)
    at AotCompiler.emitAllImpls (C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler\bundles\compiler.umd.js:27226:39)
    at AngularCompilerProgram.generateFilesForEmit (C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler-cli\src\transformers\program.js:633:46)
    at AngularCompilerProgram._emitRender2 (C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler-cli\src\transformers\program.js:218:27)
    at AngularCompilerProgram.emit (C:\Projects\Agency004\Testing\angular10\angular10Test\node_modules\@angular\compiler-cli\src\transformers\program.js:200:25)

**It builds successfully when Ivy is enabled. I would expect it to work also with Ivy set as disabled.**

- Library version: [3.0]
**ng --version output:**

Angular CLI: 10.2.1
Node: 12.20.0
OS: win32 x64

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: No

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.1
@angular-devkit/build-angular   0.1002.1
@angular-devkit/core            10.2.1
@angular-devkit/schematics      10.2.1
@angular/cli                    10.2.1
@schematics/angular             10.2.1
@schematics/update              0.1002.1
ng-packagr                      10.1.2
rxjs                            6.6.3
typescript                      4.0.5
webpack                         4.44.2

 - OS: Windows 10 Pro
 - Browser chrome 87.0.4280.88 (Official Build) (64-bit)

**Comment by Xymmer** [comment]
@dinolaktasic as this issue was reported in December, that was a while ago, are you still seeing it?
I'm closing for now, but contact me if it's still an issue.

**Comment by dunqan** [comment]
@dinolaktasic can you maybe explain your reasons, why you want to run Spartacus 3.0 without Ivy enabled?

We are leveraging some Ivy features in Spartacus 3.0 for some core functionalities, making it work without Ivy may require a bit more effort than just disabling the flag, therefore I would not recommend doing it until there is a really jutified reason.
