### ISSUE TITLE
Backend Spartacus Recipe Properties Update. OCC Path

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7570]
Add property occ.rewrite.overlapping.paths.enabled so that new OCC routing in 2005 takes effect. 

In the case of swagger, wrong endpoint is: 
/rest/v2/swagger-ui.html

Correct endpoint is: 
**/occ/v2/swagger-ui.html**

**Comment by giancorderoortiz** [comment]
Related to https://github.com/SAP/spartacus/issues/7237

**Comment by giancorderoortiz** [comment]
pr https://github.tools.sap/cx-commerce/c3po-legacy-devconfigs/pull/22

**Comment by giancorderoortiz** [comment]
pr merged

**Comment by giancorderoortiz** [comment]
This update also here: https://github.tools.sap/cx-commerce/c3po-legacy-devconfigs/pull/24
which is a new version of spartacus recipe based on cx recipe.

**Comment by KateChuen** [comment]
Tested previously with only the changes in the PR-22 and it didn't work.
Then tested again with the PR-24 as well, on dev3 with cs 200511004. 
Was able to access https://dev-com-3.accdemo.b2c.ydev.hybris.com:9002/occ/v2/swagger-ui.html
Therefore the occ path is ok now. 

But I got this error during init:
```
ERROR [main] [HybrisApplicationEventMulticaster] No bean named 'sapProductConfigConfigurationProvider' available
     [java] org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'sapProductConfigConfigurationProvider' available
     [java]     at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:805) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
     [java]     at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1278) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
     [java]     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:297) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
     [java]     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:276) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
     [java]     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
     [java]     at org.springframework.beans.factory.support.CglibSubclassingInstantiationStrategy$LookupOverrideMethodInterceptor.intercept(CglibSubclassingInstantiationStrategy.java:242) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
     [java]     at de.hybris.platform.sap.productconfig.services.event.impl.ProductConfigAfterInitializationStartEventListener$$EnhancerBySpringCGLIB$$1acee9df.getConfigurationProviderCPS(<generated>) ~[classes/:?]
     [java]     at de.hybris.platform.sap.productconfig.services.event.impl.ProductConfigAfterInitializationStartEventListener.releaseConfigs(ProductConfigAfterInitializationStartEventListener.java:151) ~[classes/:?]
```


Error during startup:
```
ERROR [localhost-startStop-3] [ContextLoader] Context initialization failed
INFO   | jvm 1    | main    | 2020/05/27 21:07:46.147 | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'selectiveCartSplitListController' method 
INFO   | jvm 1    | main    | 2020/05/27 21:07:46.147 | de.hybris.platform.selectivecartsplitlistaddon.controllers.pages.SelectiveCartSplitListController#checkCartEntries(String, RedirectAttributes)
INFO   | jvm 1    | main    | 2020/05/27 21:07:46.147 | to {POST /cart/entries/check}: There is already 'selectiveCartController' bean method
```

**Comment by KateChuen** [comment]
GC says "This was supposed to be a temporary solution. But there were issues with b2b". Closing this ticket since the occ path works, which is the purpose of the ticket.
